function createfigure(XData1, YData1, YData2, YData3, YData4, YData5, Parent1)
%CREATEFIGURE(XData1, YData1, YData2, YData3, YData4, YData5, Parent1)
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  YDATA2:  line ydata
%  YDATA3:  line ydata
%  YDATA4:  line ydata
%  YDATA5:  line ydata
%  PARENT1:  text parent

%  Auto-generated by MATLAB on 10-Apr-2022 22:25:10

% Create figure
figure('InvertHardcopy','off','Tag','ScopePrintToFigure','Color',[1 1 1]);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uicontainer currently does not support code generation, enter 'doc uicontainer' for correct input syntax
% In order to generate code for uicontainer, you may use GUIDE. Enter 'doc guide' for more information
% uicontainer(...);

% uipanel currently does not support code generation, enter 'doc uipanel' for correct input syntax
% In order to generate code for uipanel, you may use GUIDE. Enter 'doc guide' for more information
% uipanel(...);

% Create axes
axes1 = axes('Tag','DisplayAxes1_RealMag',...
    'Position',[0.0393229157586272 0.078678676799253 0.950130209509128 0.903303305182729]);
hold(axes1,'on');
colororder([0 0.447058823529412 0.741176470588235;0.850980392156863 0.325490196078431 0.0980392156862745;0.929411764705882 0.694117647058824 0.125490196078431;0.494117647058824 0.184313725490196 0.556862745098039;0.466666666666667 0.674509803921569 0.188235294117647;0.301960784313725 0.745098039215686 0.933333333333333;0.635294117647059 0.0784313725490196 0.184313725490196]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create hgtransform
hgtransform('HitTest','off','Matrix',[1 0 0 0;0 1 0 0;0 0 1 0;0 0 0 1]);

% Create line
line(XData1,YData1,'DisplayName','agent_0/1','Tag','DisplayLine1',...
    'MarkerSize',8,...
    'LineWidth',3);

% Create line
line(XData1,YData2,'DisplayName','agent_1/1','Tag','DisplayLine2',...
    'MarkerSize',8,...
    'LineWidth',3,...
    'Color',[0.749019607843137 0.749019607843137 0]);

% Create line
line(XData1,YData3,'DisplayName','agent_2/1','Tag','DisplayLine3',...
    'LineWidth',3,...
    'Color',[1 0.411764705882353 0.16078431372549]);

% Create line
line(XData1,YData4,'DisplayName','agent_3/1','Tag','DisplayLine4',...
    'LineWidth',3,...
    'Color',[0.850980392156863 0.325490196078431 0.0980392156862745]);

% Create line
line(XData1,YData5,'DisplayName','agent_4/1','Tag','DisplayLine5',...
    'LineWidth',3,...
    'Color',[0.717647058823529 0.274509803921569 1]);

% Create ylabel
ylabel('Output Voltage','FontSize',12);

% Create xlabel
xlabel('Time (ms)','FontSize',12);

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 0.25]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-51.4477831361749 51.4477754361246]);
% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[-1 1]);
box(axes1,'on');
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'ClippingStyle','rectangle','GridAlpha',0.4,'GridColor',[0 0 0],...
    'SortMethod','childorder','TickLabelInterpreter','none','XGrid','on',...
    'XTick',[0 0.05 0.1 0.15 0.2 0.25],'XTickLabel',...
    {'0','50','100','150','200','250'},'YGrid','on','YTick',...
    [-50 -40 -30 -20 -10 0 10 20 30 40 50],'YTickLabel',...
    {'-50','-40','-30','-20','-10','0','10','20','30','40','50'});
% Create legend
legend1 = legend(axes1,'show');
set(legend1,'Units','pixels',...
    'Position',[1142.3364529335 464.333341884111 110.999998211861 85.9999976158142],...
    'Interpreter','none',...
    'FontSize',10,...
    'EdgeColor',[0 0 0]);

% Create text
text('Tag','TimeOffsetStatus','Parent',Parent1,'Units','pixels',...
    'VerticalAlignment','bottom',...
    'String','Offset=0',...
    'Position',[0 0 0],...
    'Visible','on');

